### ISSUE TITLE
incorrect value for feature person in rules

### ISSUE THREAD

**Issue by pkolb** [natalieahn/espmorfo#1]
In [espmorfo_rules.xlsx](https://github.com/natalieahn/espmorfo/blob/master/rulefiles/espmorfo_rules.xlsx) in cell (209;G) the value for person is "third" but it should be "second" (for morph_ending "iste").

**Comment by natalieahn** [comment]
Great catch, thanks! Just uploaded new version.

**Comment by natalieahn** [comment]
Welcome any other issues, nice to see someone using this!
